### PR TITLE
Add BatchUpdate

### PR DESCRIPTION
**Pull request by piecubed**
First version of a BatchUpdate class.  Totally open to any changes!

### CODE REVIEW

**Comment by piecubed** [comment]
Oh, I just saw https://github.com/a-marenkov/gsheets/blob/master/lib/src/gsheets.dart#L132
Well, this can be a nice user facing way I guess

**Comment by a-marenkov** [comment]
> Oh, I just saw https://github.com/a-marenkov/gsheets/blob/master/lib/src/gsheets.dart#L132
> Well, this can be a nice user facing way I guess

Hi, i merged https://github.com/a-marenkov/gsheets/pull/10 and rolled out new dev version of gsheets with **createSpreadsheet**. I also added **batchUpdate** method to **Spreadsheet** and exposed one in **Gsheets** here is the [commit](https://github.com/a-marenkov/gsheets/commit/0497df88dd92827089ab56c41d218bef02c3da0a). 

This way it might be sufficient for batch update functionality, what do you think? Or you'd prefer to have BatchUpdate class?

Thanks for contributing and enthusiasm :)

P.S. Actually, i've planed to create class Table that holds mutable rows and columns and has a sync method. So user would fetch the worksheet, manimpulate it, change its cells and then just sync it.
But i have not thought this through and i don't really have the time for it now.

**Comment by piecubed** [comment]
@a-marenkov I'm going to be on summer break soon, so if you could create a project with some specific things you would like to add, I'd be happy to make PRs.

**Comment by piecubed** [comment]
I kind of like the idea of an actual queue you can change later, and apply to more than one spreadsheet, like a template, so I would say a class might be better.  For a mutable sync spreadsheet, this might be better, because it would already have the queue implemented.  It's not hard to make a queue though, so it's up to you if you want to merge this or not.

**Comment by piecubed** [comment]
Any thoughts on this?

**Comment by a-marenkov** [comment]
> Any thoughts on this?

Well, i'm not against the BatchUpdate class, but i don't really see what this implementation brings. 

I think users can create list of requests by themselves and then call Gsheets.batchUpdate if they want to apply them to more than one spreadsheet or if they don't want to fetch the spreadsheet beforehand, otherwise they can use batchUpdate of Spreadsheet class.

This implementation also forces them to use googleapis library (i don't know it might be good, might be not).

So again, i'm not against the BatchUpdate class, i just need to think about it.

**Comment by piecubed** [comment]
@a-marenkov Could you make a project for this repo?  Just put things you want to be implemented in there, as I don't really know what you want to happen next.

**Pull request closed without merging**
